<?php

return [
    'currencies' => [
        ['value' => '', 'label' => 'Select currency'],
        ['value' => 'USD', 'label' => 'United States Dollars – USD'],
        ['value' => 'AFN', 'label' => 'Afghanistan Afghanis – AFN'],
        ['value' => 'ALL', 'label' => 'Albania Leke – ALL'],
        ['value' => 'DZD', 'label' => 'Algeria Dinars – DZD'],
        ['value' => 'ARS', 'label' => 'Argentina Pesos – ARS'],
        ['value' => 'AUD', 'label' => 'Australia Dollars – AUD'],
        ['value' => 'ATS', 'label' => 'Austria Schillings – ATS'],
        ['value' => 'BSD', 'label' => 'Bahamas Dollars – BSD'],
        ['value' => 'BHD', 'label' => 'Bahrain Dinars – BHD'],
        ['value' => 'BDT', 'label' => 'Bangladesh Taka – BDT'],
        ['value' => 'BBD', 'label' => 'Barbados Dollars – BBD'],
        ['value' => 'BEF', 'label' => 'Belgium Francs – BEF'],
        ['value' => 'BMD', 'label' => 'Bermuda Dollars – BMD'],
        ['value' => 'BRL', 'label' => 'Brazil Reais – BRL'],
        ['value' => 'BGN', 'label' => 'Bulgaria Leva – BGN'],
        ['value' => 'CAD', 'label' => 'Canada Dollars – CAD'],
        ['value' => 'XOF', 'label' => 'CFA BCEAO Francs – XOF'],
        ['value' => 'XAF', 'label' => 'CFA BEAC Francs – XAF'],
        ['value' => 'CLP', 'label' => 'Chile Pesos – CLP'],
        ['value' => 'CNY', 'label' => 'China Yuan Renminbi – CNY'],
        ['value' => 'COP', 'label' => 'Colombia Pesos – COP'],
        ['value' => 'XPF', 'label' => 'CFP Francs – XPF'],
        ['value' => 'CRC', 'label' => 'Costa Rica Colones – CRC'],
        ['value' => 'HRK', 'label' => 'Croatia Kuna – HRK'],
        ['value' => 'CYP', 'label' => 'Cyprus Pounds – CYP'],
        ['value' => 'CZK', 'label' => 'Czech Republic Koruny – CZK'],
        ['value' => 'DKK', 'label' => 'Denmark Kroner – DKK'],
        ['value' => 'DEM', 'label' => 'Deutsche (Germany) Marks – DEM'],
        ['value' => 'DOP', 'label' => 'Dominican Republic Pesos – DOP'],
        ['value' => 'NLG', 'label' => 'Dutch (Netherlands) Guilders – NLG'],
        ['value' => 'XCD', 'label' => 'Eastern Caribbean Dollars – XCD'],
        ['value' => 'EGP', 'label' => 'Egypt Pounds – EGP'],
        ['value' => 'EEK', 'label' => 'Estonia Krooni – EEK'],
        ['value' => 'EUR', 'label' => 'Euro – EUR'],
        ['value' => 'FJD', 'label' => 'Fiji Dollars – FJD'],
        ['value' => 'FIM', 'label' => 'Finland Markkaa – FIM'],
        ['value' => 'FRF', 'label' => 'France Francs – FRF*'],
        ['value' => 'DEM', 'label' => 'Germany Deutsche Marks – DEM'],
        ['value' => 'XAU', 'label' => 'Gold Ounces – XAU'],
        ['value' => 'GRD', 'label' => 'Greece Drachmae – GRD'],
        ['value' => 'GTQ', 'label' => 'Guatemalan Quetzal – GTQ'],
        ['value' => 'NLG', 'label' => 'Holland (Netherlands) Guilders – NLG'],
        ['value' => 'HKD', 'label' => 'Hong Kong Dollars – HKD'],
        ['value' => 'HUF', 'label' => 'Hungary Forint – HUF'],
        ['value' => 'ISK', 'label' => 'Iceland Kronur – ISK'],
        ['value' => 'XDR', 'label' => 'IMF Special Drawing Right – XDR'],
        ['value' => 'INR', 'label' => 'India Rupees – INR'],
        ['value' => 'IDR', 'label' => 'Indonesia Rupiahs – IDR'],
        ['value' => 'IRR', 'label' => 'Iran Rials – IRR'],
        ['value' => 'IQD', 'label' => 'Iraq Dinars – IQD'],
        ['value' => 'IEP', 'label' => 'Ireland Pounds – IEP*'],
        ['value' => 'ILS', 'label' => 'Israel New Shekels – ILS'],
        ['value' => 'ITL', 'label' => 'Italy Lire – ITL*'],
        ['value' => 'JMD', 'label' => 'Jamaica Dollars – JMD'],
        ['value' => 'JPY', 'label' => 'Japan Yen – JPY'],
        ['value' => 'JOD', 'label' => 'Jordan Dinars – JOD'],
        ['value' => 'KES', 'label' => 'Kenya Shillings – KES'],
        ['value' => 'KRW', 'label' => 'Korea (South) Won – KRW'],
        ['value' => 'KWD', 'label' => 'Kuwait Dinars – KWD'],
        ['value' => 'LBP', 'label' => 'Lebanon Pounds – LBP'],
        ['value' => 'LUF', 'label' => 'Luxembourg Francs – LUF'],
        ['value' => 'MYR', 'label' => 'Malaysia Ringgits – MYR'],
        ['value' => 'MTL', 'label' => 'Malta Liri – MTL'],
        ['value' => 'MUR', 'label' => 'Mauritius Rupees – MUR'],
        ['value' => 'MXN', 'label' => 'Mexico Pesos – MXN'],
        ['value' => 'MAD', 'label' => 'Morocco Dirhams – MAD'],
        ['value' => 'NLG', 'label' => 'Netherlands Guilders – NLG'],
        ['value' => 'NZD', 'label' => 'New Zealand Dollars –NZD'],
        ['value' => 'NOK', 'label' => 'Norway Kroner – NOK'],
        ['value' => 'OMR', 'label' => 'Oman Rials – OMR'],
        ['value' => 'PKR', 'label' => 'Pakistan Rupees – PKR'],
        ['value' => 'XPD', 'label' => 'Palladium Ounces – XPD'],
        ['value' => 'PEN', 'label' => 'Peru Nuevos Soles – PEN'],
        ['value' => 'PHP', 'label' => 'Philippines Pesos – PHP'],
        ['value' => 'XPT', 'label' => 'Platinum Ounces – XPT'],
        ['value' => 'PLN', 'label' => 'Poland Zlotych – PLN'],
        ['value' => 'PTE', 'label' => 'Portugal Escudos – PTE'],
        ['value' => 'QAR', 'label' => 'Qatar Riyals – QAR'],
        ['value' => 'RON', 'label' => 'Romania New Lei – RON'],
        ['value' => 'ROL', 'label' => 'Romania Lei – ROL'],
        ['value' => 'RUB', 'label' => 'Russia Rubles – RUB'],
        ['value' => 'SAR', 'label' => 'Saudi Arabia Riyals – SAR'],
        ['value' => 'XAG', 'label' => 'Silver Ounces – XAG'],
        ['value' => 'SGD', 'label' => 'Singapore Dollars – SGD'],
        ['value' => 'SKK', 'label' => 'Slovakia Koruny – SKK'],
        ['value' => 'SIT', 'label' => 'Slovenia Tolars – SIT'],
        ['value' => 'ZAR', 'label' => 'South Africa Rand – ZAR'],
        ['value' => 'KRW', 'label' => 'South Korea Won – KRW'],
        ['value' => 'ESP', 'label' => 'Spain Pesetas – ESP'],
        ['value' => 'XDR', 'label' => 'Special Drawing Rights (IMF) – XDR'],
        ['value' => 'LKR', 'label' => 'Sri Lanka Rupees – LKR'],
        ['value' => 'SDD', 'label' => 'Sudan Dinars – SDD'],
        ['value' => 'SEK', 'label' => 'Sweden Kronor – SEK'],
        ['value' => 'CHF', 'label' => 'Switzerland Francs – CHF'],
        ['value' => 'TWD', 'label' => 'Taiwan New Dollars – TWD'],
        ['value' => 'THB', 'label' => 'Thailand Baht – THB'],
        ['value' => 'TTD', 'label' => 'Trinidad and Tobago Dollars – TTD'],
        ['value' => 'TND', 'label' => 'Tunisia Dinars – TND'],
        ['value' => 'TRY', 'label' => 'Turkey New Lira – TRY'],
        ['value' => 'AED', 'label' => 'United Arab Emirates Dirhams – AED'],
        ['value' => 'GBP', 'label' => 'United Kingdom Pounds – GBP'],
        ['value' => 'USD', 'label' => 'United States Dollars – USD'],
        ['value' => 'VEB', 'label' => 'Venezuela Bolivares – VEB'],
        ['value' => 'VND', 'label' => 'Vietnam Dong – VND'],
        ['value' => 'ZMK', 'label' => 'Zambia Kwacha – ZMK'],
    ],
];
